### ISSUE TITLE
在线体验地址登录不了

### ISSUE THREAD

**Issue by dengyao0215** [electronic-pig/gkvr_system_backend#1]
本地代码调试也跑不起来，应该是在线数据源的问题，请问数据库能否共享一下呢

**Comment by electronic-pig** [comment]
在线体验的服务器应该是寄了:cry:
[gkvr_system.zip](https://github.com/electronic-pig/gkvr_system_backend/files/13258656/gkvr_system.zip)
上面是数据库文件，请根据实际的情况配置环境:rocket:，注意我们不保证数据的准确性，仅做展示用:pray:
如果对你有帮助的话，麻烦点个:star:,谢谢！
