### ISSUE TITLE
最新的数据库

### ISSUE THREAD

**Issue by heng-shan** [electronic-pig/gkvr_system_backend#12]
有最新的数据库嘛，上面的数据库有些字段对不上，多谢作者

**Comment by electronic-pig** [comment]
这是新的数据库脚本文件
[gkvr_system.zip](https://github.com/electronic-pig/gkvr_system_backend/files/14770581/gkvr_system.zip)，mysql的版本是5.7，目前这个项目还在重构维护过程中，有些功能接口还没有实现
