### ISSUE TITLE
问一下这个项目的数据库源文件或者sql脚本，非常感谢 

### ISSUE THREAD

**Issue by suheng1234567890** [electronic-pig/gkvr_system_backend#18]

**Comment by electronic-pig** [comment]
已在[Releases](https://github.com/electronic-pig/gkvr_system_backend/releases)中的Assets里提供，对你有帮助的话麻烦点个star，感谢

**Comment by suheng1234567890** [comment]
好的非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月12日(周五) 下午4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [electronic-pig/gkvr_system_backend] 问一下这个项目的数据库源文件或者sql脚本，非常感谢  (Issue #18)




 
已在Releases中的Assets里提供，对你有帮助的话麻烦点个star，感谢
