### ISSUE TITLE
您好，没有找到包含推荐方法的类？

### ISSUE THREAD

**Issue by TMoon1** [electronic-pig/gkvr_system_backend#20]
您好，我在您其他的问题中看到推荐方法详见VoluntaryRecoServiceImpl类，是在后端代码Impl包中吗？找了好久没有看到呢

**Comment by electronic-pig** [comment]
后端的代码是重构后的2.0.0版本，以前的代码已不适用，另外这项目实际没什么推荐算法，就是简单的数学计算，建议自己设计算法

**Comment by TMoon1** [comment]
> 后端的代码是重构后的2.0.0版本，以前的代码已不适用，另外这项目实际没什么推荐算法，就是简单的数学计算，建议自己设计算法

好的喔，谢谢您
