### ISSUE TITLE
数据库请求！

### ISSUE THREAD

**Issue by LucidX2002** [electronic-pig/gkvr_system_backend#22]
您好，已经拜读您的代码，写的很漂亮！
我需要一下数据库后端，进行推荐系统的制作！感谢！我的邮箱是847232511@qq.com

**Comment by electronic-pig** [comment]
数据库脚本已在[Releases](https://github.com/electronic-pig/gkvr_system_backend/releases)中的Assets里提供，如果项目对您有用的话麻烦点个 ⭐

**Comment by TestInShangHai** [comment]
不错···已关注
