### ISSUE TITLE
体验端无法登录

### ISSUE THREAD

**Issue by whc789** [electronic-pig/gkvr_system_backend#27]
您好，体验端登录一直转圈是无法使用了吗。还有我这边部署时遇到一个问题，在进入个性化志愿推荐时Request failed with status code 500报错，具体错误信息我附一张图吧。后端在运行到图二时会报错。
![图1](https://github.com/electronic-pig/gkvr_system_backend/assets/150577333/d495deaa-3ab8-4d37-ae2f-033097eaf2a7)
![图2](https://github.com/electronic-pig/gkvr_system_backend/assets/150577333/9e9737ae-2bdb-4eac-af29-b8f94cadc606)

**Comment by whc789** [comment]
经验不足希望您能赐教

**Comment by electronic-pig** [comment]
服务器不太行所以偶尔登不上，你可以再试试，报错的问题目前仅凭截图我也看不太出来，可以检查一下你的mysql版本，我用的是5.7

**Comment by whc789** [comment]
好的感谢老哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年6月4日(星期二) 晚上11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [electronic-pig/gkvr_system_backend] 体验端无法登录 (Issue #27)














 
服务器不太行所以偶尔登不上，你可以再试试，报错的问题目前仅凭截图我也看不太出来，可以检查一下你的mysql版本，我用的是5.7

**Comment by whc789** [comment]
解决了老哥，确实是mysql版本问题我的版本太高了把字段rank识别成保留字了，加一个@TableField(value = "`rank`")就可以了，非常感谢，老哥及时回复哈
