### ISSUE TITLE
gkvr_system_backend

### ISSUE THREAD

**Issue by wushaohuang** [electronic-pig/gkvr_system_backend#28]
你好，

感谢开源项目“高考志愿推荐平台_后端”，对我学习借鉴有很大帮助，在项目中提到数据库文件需通过提issue的方式获取，请问我该如何获取？

谢谢！

**Comment by electronic-pig** [comment]
数据库脚本已在[Releases](https://github.com/electronic-pig/gkvr_system_backend/releases)中的Assets里提供，如果项目对您有用的话麻烦点个 ⭐
