### ISSUE TITLE
老师请教个问题，宝塔搭建完高考志愿项目启动后访问提示如下图

### ISSUE THREAD

**Issue by xiaolongwanga** [electronic-pig/gkvr_system_backend#29]
[image](https://github.com/electronic-pig/gkvr_system_backend/assets/161673849/9404ca0a-b4b0-42e6-a2e5-782170374051)
百度很多方法都试了没用，希望老师帮忙解答下。

**Comment by electronic-pig** [comment]
我没用过宝塔，所以不太清楚，可能是springboot里需要一些额外的配置，你可以试试问问GPT
