### ISSUE TITLE
有爬取相关数据的源码吗

### ISSUE THREAD

**Issue by zhangjl666** [electronic-pig/gkvr_system_backend#5]
请问有爬取掌上高考数据源码吗

**Comment by weeadd** [comment]
[爬虫代码.zip](https://github.com/electronic-pig/gkvr_system_backend/files/13778974/default.zip)
这是当时使用的爬虫源码，但仅作为一次性工具来编写使用，并不是很规范，具体问题还需自行调整

**Comment by zhangjl666** [comment]
> [爬虫代码.zip](https://github.com/electronic-pig/gkvr_system_backend/files/13778974/default.zip) 这是当时使用的爬虫源码，但仅作为一次性工具来编写使用，并不是很规范，具体问题还需自行调整

xd,有几个关于数据的问题，有几个数据源https://api.eol.cn/web/api，https://static-data.gaokao.cn是哪里的呢，能否显示的看到里面的数据，我怎么知道是哪些学校、专业，那个省份那一年的数据呢

**Comment by weeadd** [comment]
这些都是分析爬取的掌上高考网[https://www.gaokao.cn/]的页面数据，你可以结合url对照来看
